apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kong
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  # Kong is scaled up in the post-install hook.
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      service: {{ template "fullname" . }}-kong
      wicked: "true"
  template:
    metadata:
      labels:
        service: {{ template "fullname" . }}-kong
        wicked: "true"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port:  '8001'
    spec:
{{- if .Values.useRbac }}
      serviceAccountName: {{ template "fullname" . }}-role
{{- end }}
{{- if .Values.postgres.deployPostgres }}
      initContainers:
      - name: {{ template "fullname" . }}-kong-init
        image: "{{ .Values.image.repository }}k8s-tool:{{ default "latest" .Values.image.tag }}"
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        args:
        - "pod"
        - "-lservice={{ template "fullname" . }}-kong-database"
{{- end }}
      containers:
      - name: {{ template "fullname" . }}-kong
        image: "{{ .Values.image.repository }}kong:{{ default "latest" .Values.image.tag }}"
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        env:
        - name: KONG_PG_HOST
{{- if .Values.postgres.deployPostgres }}
          value: {{ template "fullname" . }}-kong-database.{{ default "default" .Values.namespace }}.svc.cluster.local
{{- else }}
          value: {{ .Values.postgres.pgHost }}
{{- end }}
        - name: KONG_PG_PORT
          value: "{{ .Values.postgres.pgPort }}"
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: pgUser
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: pgPassword
        - name: KONG_PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: pgDatabase
{{- if .Values.postgres.pgSsl }}
        - name: KONG_PG_SSL
          value: "on"
{{- end }}
        - name: KONG_HEADERS
          value: {{ .Values.kong.headers | quote }}
        readinessProbe:
          exec:
            command:
              - kong
              - health
        ports:
        - name: "gateway"
          containerPort: 8000
          protocol: TCP
        - name: "admin"
          containerPort: 8001
          protocol: TCP
        - name: "advertise"
          containerPort: 7946
          protocol: TCP
        - name: "advertiseudp"
          containerPort: 7946
          protocol: UDP
        resources:
{{ toYaml .Values.kong.resources | indent 10 }}
      restartPolicy: Always
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end -}}