{{- if .Values.deployChatbot -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-chatbot
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- with .Values.deployments.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      service: {{ template "fullname" . }}-chatbot
      wicked: "true"
  template:
    metadata:
      labels:
        service: {{ template "fullname" . }}-chatbot
        wicked: "true"
    spec:
{{- if .Values.useRbac }}
      serviceAccountName: {{ template "fullname" . }}-role
{{- end }}
      initContainers:
      - name: {{ template "fullname" . }}-chatbot-init
        image: "{{ .Values.image.repository }}k8s-tool:{{ default "latest" .Values.image.tag }}"
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        args:
        - "pod"
        - "-lservice={{ template "fullname" . }}-api"
      containers:
      - name: {{ template "fullname" . }}-chatbot
        image: "{{ .Values.image.repository }}chatbot:{{ default "latest" .Values.image.tag }}{{ if .Values.image.alpine }}-alpine{{ end }}"
        imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-apim-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-apim-config
              key: LOG_LEVEL
        - name: PORTAL_API_URL
          value: "http://{{ template "fullname" . }}-api.{{ default "default" .Values.namespace }}.svc.cluster.local:3001/"
        ports:
        - containerPort: 3004
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.resources.chatbot | indent 10 }}
      restartPolicy: Always
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end -}}
{{- end -}}
