{{- if .Values.redis.deployRedis }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- with .Values.deployments.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: {{ template "fullname" . }}-redis
      wicked: "true"
  template:
    metadata:
      labels:
        service: {{ template "fullname" . }}-redis
        wicked: "true"
    spec:
{{- if .Values.useRbac }}
      serviceAccountName: {{ template "fullname" . }}-role
{{- end }}
      containers:
      - name: {{ template "fullname" . }}-redis
        image: {{ default "redis:3.2.10-alpine" .Values.redis.image }} 
        ports:
        - name: "redis"
          containerPort: 6379
          protocol: TCP
      restartPolicy: Always
{{- end -}}
